=== Evil-Co-Legacy/Ikarus/XSD/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ikarus-framework.de" xmlns="http://www.ikarus-framework.de" elementFormDefault="qualified">
	<!--
	Ikarus Framework Database Specification
	author:		Johannes Donath
	updated:	10.04.2011
	version:	1.0.0
	-->

	<!-- Include basic ikarus types -->
	<xs:include schemaLocation="http://www.ikarus-framework.de/XSD/types.xsd" />

	<!-- Define root element -->
	<xs:element name="database">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="instruction" type="instruction" minOccurs="1" maxOccurs="unbounded" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<!-- Define instruction element -->
	<xs:complexType name="instruction">
		<xs:sequence>
			<xs:choice>
				<xs:element name="row" type="row" />
				<xs:element name="table" type="table" />
			</xs:choice>
		</xs:sequence>
		
		<!-- Action argument (Defines what ikarus should do) -->
		<xs:attribute name="action" type="instructionType" />
		
		<!-- Table argument (Defines on what table the action should executed) -->
		<xs:attribute name="table" type="xs:string" />
	</xs:complexType>
	
	<!-- Define row element -->
	<xs:complexType name="row">
		<xs:sequence>
			<xs:element name="field">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Define table element -->
	<xs:complexType name="table">
		<xs:sequence>
			<xs:element name="field">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string" />
							<xs:attribute name="type" type="xs:string" />
							<xs:attribute name="length" type="xs:integer" />
							<xs:attribute name="key" type="xs:string" />
							<xs:attribute name="autoincrement" type="ikarus_boolean" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Defines allowed actions -->
	<xs:simpleType name="instructionType">
		<xs:restriction base="xs:string">
			<!-- CREATE TABLE -->
			<xs:enumeration value="create" />
			
			<!-- ALTER TABLE -->
			<xs:enumeration value="alter" />
			
			<!-- DROP TABLE -->
			<xs:enumeration value="drop" />
			
			<!-- UPDATE -->
			<xs:enumeration value="update" />
			
			<!-- INSERT INTO -->
			<xs:enumeration value="insert" />
			
			<!-- DELETE FROM -->
			<xs:enumeration value="delete" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Evil-Co-Legacy/Ikarus/contrib/example.database.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns="http://www.ikarus-framework.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ikarus-framework.de http://www.ikarus-framework.de/XSD/database.xsd">
	<!-- Create tabl example_01 -->
	<instruction action="create" table="example_01">
		<table>
			<field name="testID" type="int" length="11" key="PRIMARY" autoincrement="1" />
			<field name="testName" type="varchar" length="255"><![CDATA[Default]]></field>
			<field name="testContent" type="text"><![CDATA[This is content
with newlines ...]]></field>
			<field name="isDisabled" type="tinyint" length="1">0</field>
		</table>
	</instruction>
	
	<!-- Alter table example_01
		  - Add testField
		  - Set default of field isDisabled to '1'
		  - Rename testField to newTestField
		  - Drop field testName
	-->
	<instruction action="alter" table="example_01">
		<table>
			<field action="add" name="testField" type="int" length="2" />
			<field action="modify" name="isDisabled">1</field>
			<field action="rename" name="testField" newname="newTestField" />
			<field action="drop" name="testName" />
		</table>
	</instruction>
	
	<!-- Drop table example_02 -->
	<instruction action="drop" table="example_02" />
	
	<!-- Update all rows WHERE NOT (field1 == 2 AND field2 != 'Text') OR field3 == 5
			- Set field1 to 1
	-->
	<instruction action="update" table="example_03">
		<conditions>
			<or>
				<not>
					<and>
						<field operator="is" name="field1">2</field>
						<field operator="isnot" name="field2"><![CDATA[Text]]></field>
					</and>
				</not>
				
				<field operator="is" name="field3">5</field>
			</or>
		</conditions>
		<row>
			<field name="field1">1</field>
		</row>
	</instruction>
	
	<!-- Insert a new row
			- INSERT INTO example_04 (field1, field2) VALUES (1, 'Text')
	 -->
	<instruction action="insert" table="example_04">
		<row>
			<field name="field1">1</field>
			<field name="field2"><![CDATA[Text]]></field>
		</row>
	</instruction>
	
	<!-- Delete all matching rows
			- DELETE FROM example_04 WHERE field1 == 1
	-->
	<instruction action="delete" table="example_04">
		<conditions>
			<field operator="is" name="field1">1</field>
		</conditions>
	</instruction>
</database>
