=== Evil-Co-Legacy/Ikarus/XSD/eventlistener.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ikarus-framework.de" xmlns="http://www.ikarus-framework.de" elementFormDefault="qualified">
	<!--
	Ikarus Framework DEventListener Specification
	author:		Johannes Donath
	updated:	11.04.2011
	version:	1.0.0
	-->

	<!-- Include basic ikarus types -->
	<xs:include schemaLocation="http://www.ikarus-framework.de/XSD/types.xsd" />
	
	<!-- Definition of root element -->
	<xs:element name="eventlistener">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="import" type="import" />
				<xs:element name="delete" type="delete" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<!-- Definition of import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="listener" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="inerhit" type="ikarus_boolean" minOccurs="0" maxOccurs="1" />
					</xs:sequence>
					
					<xs:attribute name="event" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- Definition of delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="listener" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="1" />
					</xs:sequence>
				
					<xs:attribute name="event" type="xs:string" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Evil-Co-Legacy/Ikarus/contrib/example.eventlistener.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventlistener xmlns="http://www.ikarus-framework.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ikarus-framework.de http://www.ikarus-framework.de/XSD/eventlistener.xsd">
	<import>
		<listener event="event@ClassName">
			<file><![CDATA[lib/system/event/listener/SampleListener.class.php]]></file>
			<inerhit>1</inerhit>
		</listener>
		
		<listener event="event2@ClassName">
			<file><![CDATA[lib/system/event/listener/SampleListener.class.php]]></file>
			<inerhit>1</inerhit>
		</listener>
	</import>
	<delete>
		<listener event="event2@ClassName">
			<file><![CDATA[lib/system/event/listener/SampleListener.class.php]]></file>
		</listener>
	</delete>
</eventlistener>
