=== Evil-Co-Legacy/Ikarus/XSD/package.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ikarus-framework.de" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
	<xs:element name="package">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="packageinformation" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="packagename" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="lang" type="xs:string" default="en" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="packagedescription" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="lang" type="xs:string" default="en" />
								</xs:complexType>
							</xs:element>

							<xs:element name="version" type="xs:string" maxOccurs="1" minOccurs="1" />
							
							<xs:element name="standalone" type="xs:integer" maxOccurs="1" minOccurs="0" default="0" />
							
							<xs:element name="plugin" type="xs:string" maxOccurs="1" minOccurs="0" default="com.develfusion.ikarus" />
							
							<xs:element name="packageurl" maxOccurs="1" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="display" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="authorinformation" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="authorname" maxOccurs="1" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="alias" type="xs:string" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="authorurl" type="xs:string" maxOccurs="1" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="requiredpackages" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="requiredpackage" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="minversion" type="xs:string" />
									<xs:attribute name="maxversion" type="xs:string" />
									<xs:attribute name="file" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="excludedpackages" maxOccurs="1" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="excludedpackage">
								<xs:complexType>
									<xs:attribute name="version" type="xs:string" />
									<xs:attribute name="startversion" type="xs:string" />
									<xs:attribute name="endversion" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<xs:element name="instructions" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="instruction" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:attribute name="type" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						
						<xs:attribute name="type" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Evil-Co-Legacy/Ikarus/contrib/example.package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package name="de.ikarus-framework.example" xmlns="http://www.ikarus-framework.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ikarus-framework.de http://www.ikarus-framework.de/XSD/package.xsd">
	<packageinformation>
		<packagename><![CDATA[Example Package]]></packagename>
		<packagename lang="de"><![CDATA[Beispiel Paket]]></packagename>
		<packagename lang="de-informal"><![CDATA[Beispiel Paket]]></packagename>
		<packagedescription><![CDATA[This is an example package.]]></packagedescription>
		<packagedescription lang="de"><![CDATA[Dies ist ein beispiel Paket.]]></packagedescription>
		<packagedescription lang="de-informal"><![CDATA[Dies ist ein beispiel Paket.]]></packagedescription>
		<version>1.0.0 Alpha 1</version>
		<plugin>com.develfusion.ikarus</plugin>
		<packageurl display="Ikarus Framework"><![CDATA[http://www.ikarus-framework.de/]]></packageurl>
		<documentationurl><![CDATA[http://www.ikarus-framework.de/doc/package/de.ikarus-framework.example-documentation.pdf]]></documentationurl>
		<developerdocumentationurl><![CDATA[http://www.ikarus-framework.de/doc/package/de.ikarus-framework.example-developer-documentation.pdf]]></developerdocumentationurl>
	</packageinformation>
	
	<authorinformation>
		<authorname alias="Akkarin"><![CDATA[Johannes Donath]]></authorname>
		<authorurl><![CDATA[http://www.ikarus-framework.de/]]></authorurl>
	</authorinformation>
	
	<licenseinformation>
		<licensename><![CDATA[GNU Lesser Public License]]></licensename>
		<licenseurl><![CDATA[http://www.gnu.org/licenses/lgpl.txt]]></licenseurl>
	</licenseinformation>
	
	<requiredpackages>
		<requiredpackage minversion="1.0.0 Alpha 1" maxversion="1.0.0">com.develfusion.ikarus</requiredpackage>
	</requiredpackages>
	
	<instructions type="install">
		<!-- Files -->
		<instruction type="acptemplates">tar/acptemplates.tar</instruction>
		<instruction type="files">tar/files.tar</instruction>
		<instruction type="templates">tar/templates.tar</instruction>
		<instruction type="packageinstallationplugins">tar/pip.tar</instruction>
		
		<!-- Imports -->
		<instruction type="database">xml/database.xml</instruction>
		<instruction type="eventlistener">xml/eventlistener.xml</instruction>
		<instruction type="groupoptions">xml/groupoptions.xml</instruction>
		<instruction type="options">xml/options.xml</instruction>
		
		<!-- Language -->
		<instruction type="language">language/en.xml</instruction>
		<instruction type="language">language/de.xml</instruction>
		<instruction type="language">language/de-informal.xml</instruction>
	</instructions>
</package>
